eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_HOST:http://localhost:8761/eureka}

spring:
  zipkin:
    baseUrl: http://zipkin-svc:9411

okta:
  oauth2:
    issuer: https://dev-33539932.okta.com/oauth2/default
    audience: api://default